version: "3.7"

services:
  architxt:
    image: architxt
    environment:
      CORENLP_URL: http://corenlp:9000
    build:
      context: .
    ports:
      - "8080:8080"

  corenlp:
    image: corenlp
    build:
      context: corenlp
    ports:
      - "9000:9000"
