[tool.poetry]
name = "architxt"
version = "0.1.0"
description = ""
authors = [
    "Nicolas Hiot <nicolas.hiot@univ-orleans.fr>",
    "Mirian Halfeld-Ferrari <mirian@univ-orleans.fr>",
    "Jacques Chabin <jchabin@univ-orleans.fr>"
]
readme = "README.md"

[tool.poetry.scripts]
architxt = "architxt.cli:main"

[tool.poetry.dependencies]
python = "^3.9"

joblib = ">=1.1"
tqdm = "*"
pqdm = "*"
nltk = "*"
chatette = ">=1.6.2"
unidecode = "*"
cachetools = "*"
pytokenizations = "0.8.4"
matplotlib = ">=3.4"
requests = "*"
scikit-learn = "*"
numpy = "*"
scipy = "*"
levenshtein = "*"
more-itertools = "*"
ray = "*"
bratlib = { git = "https://github.com/swfarnsworth/bratlib.git" }
mlflow = "^2.6.0"
numba = "^0.57.1"
shelved-cache = "^0.3.1"
typer = "^0.12.5"
anyio = "^4.6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ruff = "^0.6.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
