from architxt.tree import Tree
from hypothesis import given

from tests.test_strategies import tree_st


@given(tree=tree_st(has_parent=False))
def test_serialization(tree: Tree) -> None:
    """
    Property-based test to verify tree (de)serialization.

    Ensures that tree serialization can be re-deserialized without any loss of information.

    :param tree: A `Tree` object generated by `tree_st`.
    """
    new_tree = Tree.fromstring(str(tree))
    assert new_tree == tree
