from pathlib import Path

from architxt.forest import export_forest_to_jsonl, import_forest_from_jsonl
from architxt.tree import Forest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from tests.test_strategies import tree_st


@settings(suppress_health_check=[HealthCheck.function_scoped_fixture])
@given(forest=st.lists(tree_st(has_parent=False), max_size=10))
def test_jsonl_export(forest: Forest, tmp_path: Path) -> None:
    """
    Property-based test to verify JSONL tree export/import.

    :param forest: A list of `Tree` object generated by `tree_st`.
    """
    file_path = tmp_path / "forest.jsonl"
    export_forest_to_jsonl(file_path, forest)
    imported_forest = list(import_forest_from_jsonl(file_path))
    assert imported_forest == forest
