name: Documentation Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: rokibhasansagar/slimhub_actions@v25.42.5
        with:
          retain: "vcs,pipx,toolcache_python,docker_buildkit,nodejs_npm"

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Minify
        run: npm install -g minify

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4

      - name: Install Dependencies
        run: poetry install --all-extras --with=docs

      - name: Build Documentation
        run: poetry run sphinx-build -M html docs _build -v
        env:
          TOKENIZERS_PARALLELISM: false
          TQDM_DISABLE: 1

      - name: HTML/CSS/JS Minifier
        run: |
          find _build/html -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' \) -exec sh -c \
          'minify "$0" > "$0.tmp" && mv "$0.tmp" "$0" && echo "$0"' {} \;

      - name: Deploy (GitHub Pages)
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _build/html
          force_orphan: true
