name: Python Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
    steps:
      - uses: rcmdnk/python-action@v1
        with:
          pre-commit: true
          pytest-tests-path: "."
          pytest-cov-path: "architxt"
          pytest-ignore: 'tests/simplification/tree_rewriting/operations/test_operations.py,dev/maccrobat.py'
          python-version: "${{ matrix.python-version }}"
        env:
          PYTEST_ADDOPTS: "--doctest-modules --beartype-skip-packages=architxt/grammar"
          TOKENIZERS_PARALLELISM: false

  build:
    name: Build package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'release' || startsWith(github.head_ref, 'ci/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          name: package-dist
          path: dist/*
          if-no-files-found: error

  publish-github:
    name: Publish (GitHub)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [ build ]
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: package-dist
          path: dist

      - run: gh release upload "${TAG_NAME}" dist/*.{tar.gz,whl}
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.release.tag_name }}

  publish-pypi:
    name: Publish (PyPI)
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'release' && 'PyPI' || 'TestPyPI' }}
    permissions:
      id-token: write
    needs: [ build ]
    if: github.event_name == 'release' || startsWith(github.head_ref, 'ci/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package-dist
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          verbose: true
          repository-url: ${{ github.event_name == 'release' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
